export const THEMES = [
  {
    id: "classic",
    name: "Classic",
    desc: "Clean white, smooth fade",
    icon: "◻",
    iconColor: "text-zinc-300",
    border: "border-zinc-600",
    activeBorder: "border-zinc-300",
    activeBg: "bg-zinc-700/20",
    previewBar: "#ffffff",
    previewGrad: "from-zinc-800 to-zinc-950",
    settings: {
      subtitleColor: "#ffffff",
      fontSize: 11,
      bold: true,
      outline: 1.5,
      shadow: 0.5,
      position: "bottom", // bottom | center | top
      transition: "fade",
      textAnimation: "none",
    },
  },
  {
    id: "neon",
    name: "Neon",
    desc: "Cyan glow, slide cuts",
    icon: "◈",
    iconColor: "text-cyan-400",
    border: "border-cyan-900",
    activeBorder: "border-cyan-400",
    activeBg: "bg-cyan-400/5",
    previewBar: "#22d3ee",
    previewGrad: "from-cyan-950 to-zinc-950",
    settings: {
      subtitleColor: "#00ffff",
      fontSize: 12,
      bold: true,
      outline: 1,
      shadow: 0,
      position: "bottom",
      transition: "slideleft",
      textAnimation: "fadeup",
    },
  },
  {
    id: "fire",
    name: "Fire",
    desc: "Yellow bold, zoom in",
    icon: "✦",
    iconColor: "text-orange-400",
    border: "border-orange-900",
    activeBorder: "border-orange-400",
    activeBg: "bg-orange-400/5",
    previewBar: "#facc15",
    previewGrad: "from-orange-950 to-zinc-950",
    settings: {
      subtitleColor: "#facc15",
      fontSize: 13,
      bold: true,
      outline: 2,
      shadow: 1,
      position: "bottom",
      transition: "zoomin",
      textAnimation: "pop",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    desc: "Subtle grey, crossfade",
    icon: "⟡",
    iconColor: "text-zinc-400",
    border: "border-zinc-700",
    activeBorder: "border-zinc-400",
    activeBg: "bg-zinc-600/10",
    previewBar: "#a1a1aa",
    previewGrad: "from-zinc-900 to-black",
    settings: {
      subtitleColor: "#e4e4e7",
      fontSize: 9,
      bold: false,
      outline: 0.5,
      shadow: 0,
      position: "bottom",
      transition: "fade",
      textAnimation: "none",
    },
  },
  {
    id: "bold",
    name: "Bold",
    desc: "Violet centered, wipe",
    icon: "⬡",
    iconColor: "text-violet-400",
    border: "border-violet-900",
    activeBorder: "border-violet-400",
    activeBg: "bg-violet-400/5",
    previewBar: "#a78bfa",
    previewGrad: "from-violet-950 to-zinc-950",
    settings: {
      subtitleColor: "#c4b5fd",
      fontSize: 15,
      bold: true,
      outline: 2.5,
      shadow: 1,
      position: "center",
      transition: "wipeleft",
      textAnimation: "pop",
    },
  },
];
